language: cpp

cache:
  ccache: true
  timeout: 1000
  directories:
    - keystores

env:
  global:
    - QTIFWVER=4.0.0
    - ARCH_ROOT_DATE=2020.11.01
    - ARCH_ROOT_URL=https://mirror.rackspace.com/archlinux
    # BT_KEY
    - secure: "hHaLRfMKI1iB/NtKRfS3E+kABSbMOycS3dW2wNmNdCpPEmGaeuBfRIiwXlPMMXYIE/47YUKCGN8vraCoW4yEJGaIsU86MpaHsBYdjNFYaTjkElKTo8d2IgS9ur/ve65Fjutd8rDRGYBcvG9FIcMMgN+rNekSy9L4eVoaFuMq5V5AkxSmQu7YMmny3DMR1+eD7E/I4tu6tde16l51mB47fyW1u/FcyJ8mIAPW5hoSvVznNxAPGd5/80NcqykfjNmTFQ2B7YJMEQPwIA/YJMq+SjOqZNyB0Q8XzN1I9HqK2D2C89dZUI6bD+Q9JNGKIyoEpJ5BzKu6oZaVBGIfCCI9Dyq/B6PCm4s5swVWkGFJzL31EKewvzP3YepszEAbiuFMLW2ye6PJat5pSU13RHVKzVS2jXoFQGdPnwU9dtIRXga1csGar3RqJDlCR2Ncz1DGv80r4Z3CFycrftgFNIRLG1cXaaN4GWM8uE38zSp0hhWyiPXay++rhRdyQU4sq2A3dEA8JqxOR1B6ngxqBgN17u1VHK2EUUZ5HHlv856SnZ1lA94J7T0CBrkRxEDLmE6fLR5n0CuHSX5iA4rRfqKmF1FfQi/IaG+EWKbACkmQGIV9+aKB30JqsJvcXLtSGTC7IzonIzIKiBhjJo7AbW45VzzmfBC3MqiNPpEwwTiRKDI="

matrix:
  include:
  - os: linux
    dist: focal
    compiler: gcc
    env:
      - ARCH_ROOT_MINGW=x86_64
      - DAILY_BUILD=1
  - os: linux
    dist: focal
    compiler: gcc
    env:
      - ARCH_ROOT_MINGW=i686
      - DAILY_BUILD=1
  - os: linux
    dist: focal
    compiler: gcc
    env:
      - ARCH_ROOT_MINGW=x86_64
      - RELEASE_BUILD=1
  - os: linux
    dist: focal
    compiler: gcc
    env:
      - ARCH_ROOT_MINGW=i686
      - RELEASE_BUILD=1
  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
      - DAILY_BUILD=1
  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
      - RELEASE_BUILD=1
  - os: osx
    osx_image: xcode10.1
    compiler: clang
  - os: osx
    osx_image: xcode10.2
    compiler: clang
  - os: osx
    osx_image: xcode10.3
    compiler: clang
  - os: osx
    osx_image: xcode11
    compiler: clang
  - os: osx
    osx_image: xcode11.1
    compiler: clang
  - os: osx
    osx_image: xcode11.2
    compiler: clang
  - os: osx
    osx_image: xcode11.3
    compiler: clang
  - os: osx
    osx_image: xcode11.4
    compiler: clang
  - os: osx
    osx_image: xcode11.5
    compiler: clang
  - os: osx
    osx_image: xcode11.6
    compiler: clang
  - os: osx
    osx_image: xcode12
    compiler: clang
  - os: osx
    osx_image: xcode12u
    compiler: clang
  - os: osx
    osx_image: xcode12.2
    compiler: clang

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

before_script: |
  if [ "${TRAVIS_OS_NAME}" = linux ]; then
    export CXX=${ARCH_ROOT_MINGW}-w64-mingw32-g++
    export COMPILESPEC=win32-g++
  elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    brew link --force qt5
    if [ "${CXX}" = g++ ]; then
      export COMPILESPEC=macx-g++
    elif [ "${CXX}" = clang++ ]; then
      export COMPILESPEC=macx-clang
    fi
  fi

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

after_success:
  - chmod +x ports/ci/travis/deploy.sh
  - ports/ci/travis/deploy.sh
  - chmod +x ports/ci/travis/upload.sh
  - ports/ci/travis/upload.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
