version: 9.0.0.{build}-{branch}
os: MinGW

image: Visual Studio 2019
 
platform:
  - x64

build:
  parallel: true
  verbosity: detailed

environment:
  global:
    PYTHON_VERSION: Python39
    # api key from https://bintray.com/profile/edit
    # encrypted in https://ci.appveyor.com/tools/encrypt
    BT_KEY:
      secure: seneRk4ppI4bquIsdweI8pd8FT0RXUvU2LOUNGSBEA28IhFQijypil2CfC3WtJxa

  matrix:
    - CMAKE_GENERATOR: MSYS Makefiles
    - CMAKE_GENERATOR: Visual Studio 16 2019 

install:
  - ports\ci\appveyor\install_deps.bat

build_script:
  - ports\ci\appveyor\build.bat

after_build:
  - ports\ci\appveyor\deploy.bat

#  - ports\ci\appveyor\push_artifacts.bat
#
#deploy_script:
#  - ports\ci\appveyor\upload.bat

notifications:
  - provider: Email
    to:
      - hipersayan.x@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
