name: Linux MinGW

on: [push, pull_request]

env:
  QTIFWVER: 4.1.1
  ARCH_ROOT_DATE: 2021.05.01
  ARCH_ROOT_URL: https://mirror.rackspace.com/archlinux
  NSIS_VERSION: 3.06.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/linux-mingw/install_deps.sh
        ./ports/ci/linux-mingw/install_deps.sh
    - name: Release Build
      if: startsWith(github.ref, 'refs/tags/')
      env:
        RELEASE_BUILD: 1
      run: |
        chmod +x ports/ci/linux-mingw/build.sh
        ./ports/ci/linux-mingw/build.sh
    - name: Release Deploy
      if: startsWith(github.ref, 'refs/tags/')
      env:
        RELEASE_BUILD: 1
      run: |
        chmod +x ports/ci/linux-mingw/deploy.sh
        ./ports/ci/linux-mingw/deploy.sh
    - name: Daily Build
      if: !startsWith(github.ref, 'refs/tags/')
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/linux-mingw/build.sh
        ./ports/ci/linux-mingw/build.sh
    - name: Daily Deploy
      if: !startsWith(github.ref, 'refs/tags/')
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/linux-mingw/deploy.sh
        ./ports/ci/linux-mingw/deploy.sh
#    - name: Upload
#      run: |
#        #chmod +x ports/ci/linux-mingw/upload.sh
#        #./ports/ci/linux-mingw/upload.sh
    - name: Linux MinGW daily build packages
      uses: actions/upload-artifact@v2
      with:
        name: linux-mingw-daily-build
        path: webcamoid-packages/*
