name: Mac

on: [push, pull_request]

env:
  QTIFWVER: 4.1.1

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/mac/install_deps.sh
        ./ports/ci/mac/install_deps.sh
    - name: Build
      run: |
        chmod +x ports/ci/mac/build.sh
        ./ports/ci/mac/build.sh
    - name: Deploy
      run: |
        chmod +x ports/ci/mac/deploy.sh
        ./ports/ci/mac/deploy.sh
    - name: Upload
      run: |
        chmod +x ports/ci/mac/upload.sh
        ./ports/ci/mac/upload.sh
