name: Windows Visual Studio

on: [push, pull_request]

env:
  CMAKE_GENERATOR: Visual Studio 16 2019
  PYTHON_VERSION: Python39

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ports\ci\windows-vs\build.bat
    - name: Deploy
      run: ports\ci\windows-vs\deploy.bat
    - name: Windows MSVC daily build packages
      uses: actions/upload-artifact@v2
      with:
        name: windows-vs-daily-build
        path: webcamoid-packages/*
