name: Windows MSYS

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          cmake
          git
          make
          pkgconf
          python3
          mingw-w64-x86_64-binutils
          mingw-w64-i686-binutils
          mingw-w64-x86_64-cmake
          mingw-w64-i686-cmake
          mingw-w64-x86_64-pkgconf
          mingw-w64-i686-pkgconf
    - name: Build
      run: ./ports/ci/windows-msys/build.sh
    - name: Deploy
      run: ./ports/ci/windows-msys/deploy.sh
    - name: Upload
      run: ./ports/ci/windows-msys/upload.sh
    - name: Windows MSYS daily build packages
      uses: actions/upload-artifact@v2
      with:
        name: windows-msys-daily-build
        path: webcamoid-packages/*
